# Generated by Django 4.2.7 on 2024-04-09 18:10

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("addon_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalstorageservice",
            name="api_url_base",
            field=models.URLField(blank=True),
        ),
    ]
