# Generated by Django 4.2.7 on 2024-07-22 12:03

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorizedstorageaccount",
            name="_temporary_oauth1_credentials",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporary_authorized_storage_account",
                to="addon_service.externalcredentials",
            ),
        ),
        migrations.AlterField(
            model_name="authorizedstorageaccount",
            name="oauth2_token_metadata",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorized_storage_accounts",
                related_query_name="%(class)s_authorized_storage_account",
                to="addon_service.oauth2tokenmetadata",
            ),
        ),
    ]
