# Generated by Django 4.2.7 on 2024-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreference",
            name="disabled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
