# Generated by Django 4.2.7 on 2024-07-02 13:13

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import addon_service.common.str_uuid_field


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuth1ClientConfig",
            fields=[
                (
                    "id",
                    addon_service.common.str_uuid_field.StrUUIDField(
                        default=addon_service.common.str_uuid_field.str_uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(editable=False)),
                ("modified", models.DateTimeField()),
                ("request_token_url", models.URLField()),
                ("auth_url", models.URLField()),
                ("access_token_url", models.URLField()),
                ("client_key", models.CharField(null=True)),
                ("client_secret", models.CharField(null=True)),
            ],
            options={
                "verbose_name": "OAuth1 Client Config",
                "verbose_name_plural": "OAuth1 Client Configs",
            },
        ),
        migrations.AddField(
            model_name="externalstorageservice",
            name="oauth1_client_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_storage_services",
                to="addon_service.oauth1clientconfig",
            ),
        ),
    ]
