# Generated by Django 4.2.7 on 2024-08-20 13:45

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuredcitationaddon",
            name="root_folder",
            field=models.CharField(blank=True),
        ),
    ]
