# Generated by Django 4.2.7 on 2024-07-03 11:01

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0002_oauth1clientconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizedstorageaccount",
            name="is_oauth1_ready",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="addon_service.OAuth2TokenMetadata"
            ),
        ),
    ]
