# Generated by Django 4.2.7 on 2024-09-10 13:51

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0002_externalstorageservice_int_supported_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuredcitationaddon",
            name="root_folder",
            field=models.CharField(blank=True),
        )
    ]
