# Generated by Django 4.2.7 on 2024-03-26 03:00

import django.contrib.postgres.fields
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ("addon_service", "0002_externalcredentials_state_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorizedstorageaccount",
            name="authorized_scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="externalstorageservice",
            name="default_scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), null=True, size=None
            ),
        ),
    ]
