# Generated by Django 4.2.7 on 2024-11-13 16:34

from django.db import (
    migrations,
    models,
)

import addon_service.external_service.storage.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0004_alter_externalstorageservice_int_supported_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalstorageservice",
            name="int_supported_features",
            field=models.IntegerField(
                null=True,
                validators=[
                    addon_service.external_service.storage.models.validate_supported_features
                ],
            ),
        ),
    ]
