# Generated by Django 4.2.7 on 2024-11-18 12:49

from django.db import (
    migrations,
    models,
)

import addon_service.external_service.citation.models
import addon_service.external_service.storage.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0005_alter_externalstorageservice_int_supported_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcitationservice",
            name="int_supported_features",
            field=models.IntegerField(
                null=True,
                validators=[
                    addon_service.external_service.citation.models.validate_supported_features
                ],
            ),
        ),
    ]
