# Generated by Django 4.2.7 on 2024-12-18 08:12

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import addon_service.external_service.computing.models


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0007_oauth2clientconfig_quirks"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizedComputingAccount",
            fields=[
                (
                    "authorizedaccount_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addon_service.authorizedaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Authorized Computing Account",
                "verbose_name_plural": "Authorized Computing Accounts",
            },
            bases=("addon_service.authorizedaccount",),
        ),
        migrations.CreateModel(
            name="ConfiguredComputingAddon",
            fields=[
                (
                    "configuredaddon_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addon_service.configuredaddon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configured Computing Addon",
                "verbose_name_plural": "Configured Computing Addons",
            },
            bases=("addon_service.configuredaddon",),
        ),
        migrations.CreateModel(
            name="ExternalComputingService",
            fields=[
                (
                    "externalservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addon_service.externalservice",
                    ),
                ),
                (
                    "int_supported_features",
                    models.IntegerField(
                        null=True,
                        validators=[
                            addon_service.external_service.computing.models.validate_supported_features
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "External Computing Service",
                "verbose_name_plural": "External Computing Services",
            },
            bases=("addon_service.externalservice",),
        ),
    ]
