# Generated by Django 4.2.7 on 2024-12-19 12:24

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        (
            "addon_service",
            "0008_authorizedcomputingaccount_configuredcomputingaddon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="externalservice",
            name="icon_name",
            field=models.FilePathField(
                blank=True,
                match=".*\\.(jpg|png|svg)$",
                null=True,
                path="/home/oleh/openscience/gravyvalet/static/provider_icons",
            ),
        ),
    ]
