# Generated by Django 4.2.7 on 2025-01-08 05:22

import pathlib

import django.contrib.postgres.fields
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0009_externalservice_icon_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalservice",
            name="api_base_url_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="externalservice",
            name="icon_name",
            field=models.FilePathField(
                blank=True,
                match=".*\\.(jpg|png|svg)$",
                null=True,
                path=pathlib.PurePosixPath("/code/addon_service/static/provider_icons"),
            ),
        ),
    ]
