# Generated by Django 4.2.7 on 2025-01-30 06:05

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("addon_service", "0010_externalservice_api_base_url_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauth2tokenmetadata",
            name="date_last_refreshed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
